performer1 = Performer.create(performer_name: "RJD2", performer_description: "hip-hop/electronic")
performer2 = Performer.create(performer_name: "Bill Burr", performer_description: "standup comedy")
performer3 = Performer.create(performer_name: "Death Grips", performer_description: "experimental hip-hop/noise rock")
performer4 = Performer.create(performer_name: "CHVRCHES", performer_description: "synth-pop")
performer5 = Performer.create(performer_name: "Blockhead", performer_description: "hip-hop/electronic")
performer6 = Performer.create(performer_name: "The Hives", performer_description: "garage rock")
performer7 = Performer.create(performer_name: "Death from Above 1979", performer_description: "dance punk")
performer8 = Performer.create(performer_name: "The New Pornographers", performer_description: "indie-pop")
performer9 = Performer.create(performer_name: "Electric Six", performer_description: "new wave/rock")
performer10 = Performer.create(performer_name: "The National", performer_description: "indie/alt-rock")
performer11 = Performer.create(performer_name: "Queens of the Stone Age", performer_description: "stoner rock")
performer12 = Performer.create(performer_name: "Florence + the Machine", performer_description: "baroque pop")
performer13 = Performer.create(performer_name: "TV on the Radio", performer_description: "indie rock")


venue1 = Venue.create(venue_name: "Radio City Music Hall", venue_description: "historic midtown theater", venue_zip_code: "10020")
venue2 = Venue.create(venue_name: "Hammerstein Ballroom", venue_description: "mid-size venue", venue_zip_code: "10001")
venue3 = Venue.create(venue_name: "Beacon Theatre", venue_description: "large theater in UWS", venue_zip_code: "10023")
venue4 = Venue.create(venue_name: "Music Hall of Williamsburg", venue_description: "small club", venue_zip_code: "11211")
venue5 = Venue.create(venue_name: "Barclays Center", venue_description: "arena", venue_zip_code: "11217")
venue6 = Venue.create(venue_name: "Webster Hall", venue_description: "small club", venue_zip_code: "10003")
venue7 = Venue.create(venue_name: "Union Transfer", venue_description: "small club", venue_zip_code: "19123")
venue8 = Venue.create(venue_name: "Bell House", venue_description: "former warehouse", venue_zip_code: "11215")
venue9 = Venue.create(venue_name: "Mercury Lounge", venue_description: "tiny club", venue_zip_code: "10002")
venue10 = Venue.create(venue_name: "Terminal 5", venue_description: "hellhole", venue_zip_code: "10019")
venue11 = Venue.create(venue_name: "Brooklyn Bowl", venue_description: "small club", venue_zip_code: "11211")
venue12 = Venue.create(venue_name: "Highline Ballroom", venue_description: "small club", venue_zip_code: "10011")
venue13 = Venue.create(venue_name: "McCarren Park", venue_description: "public park", venue_zip_code: "11211")


Gig.create(performer_id: performer1.id, venue_id: venue11.id, date: "1/13/15")
Gig.create(performer_id: performer1.id, venue_id: venue12.id, date: "3/7/10")
Gig.create(performer_id: performer2.id, venue_id: venue3.id, date: "11/8/13")
Gig.create(performer_id: performer3.id, venue_id: venue4.id, date: "11/12/12")
Gig.create(performer_id: performer3.id, venue_id: venue6.id, date: "7/7/15")
Gig.create(performer_id: performer3.id, venue_id: venue7.id, date: "7/10/15")
Gig.create(performer_id: performer4.id, venue_id: venue10.id, date: "5/2/14")
Gig.create(performer_id: performer4.id, venue_id: venue13.id, date: "6/15/14")
Gig.create(performer_id: performer7.id, venue_id: venue10.id, date: "11/28/14")
Gig.create(performer_id: performer8.id, venue_id: venue8.id, date: "6/20/10")
Gig.create(performer_id: performer8.id, venue_id: venue2.id, date: "11/17/14")
Gig.create(performer_id: performer8.id, venue_id: venue10.id, date: "12/6/10")
Gig.create(performer_id: performer9.id, venue_id: venue9.id, date: "10/27/12")
Gig.create(performer_id: performer10.id, venue_id: venue5.id, date: "6/5/13")
Gig.create(performer_id: performer10.id, venue_id: venue3.id, date: "12/14/11")
Gig.create(performer_id: performer10.id, venue_id: venue10.id, date: "6/29/10")
Gig.create(performer_id: performer11.id, venue_id: venue10.id, date: "3/25/11")
Gig.create(performer_id: performer11.id, venue_id: venue5.id, date: "12/14/13")
Gig.create(performer_id: performer12.id, venue_id: venue10.id, date: "11/2/10")
Gig.create(performer_id: performer12.id, venue_id: venue1.id, date: "5/8/12")
Gig.create(performer_id: performer13.id, venue_id: venue1.id, date: "4/13/11")


User.create(email: "philrosehill@gmail.com", password: "password", name: "Phil", rank: "5", user_zip_code: "11222")
User.create(email: "test1@test.com", password: "password", name: "Rob", rank: "4", user_zip_code: "10001")
User.create(email: "test2@test.com", password: "password", name: "Russell", rank: "3", user_zip_code: "11731")
User.create(email: "test3@test.com", password: "password", name: "Tina", rank: "1", user_zip_code: "10022")
User.create(email: "test4@test.com", password: "password", name: "Ryan", rank: "2", user_zip_code: "10005")
User.create(email: "test5@test.com", password: "password", name: "Katie", rank: "1", user_zip_code: "10001")
User.create(email: "test6@test.com", password: "password", name: "Lei", rank: "2", user_zip_code: "03889")
User.create(email: "test7@test.com", password: "password", name: "Nina", rank: "1", user_zip_code: "10001")
User.create(email: "test8@test.com", password: "password", name: "Dan", rank: "1", user_zip_code: "10001")
User.create(email: "test9@test.com", password: "password", name: "Conor", rank: "1", user_zip_code: "10001")
User.create(email: "test10@test.com", password: "password", name: "Sue", rank: "1", user_zip_code: "10001")
User.create(email: "test11@test.com", password: "password", name: "Lauren", rank: "1", user_zip_code: "10001")
User.create(email: "test12@test.com", password: "password", name: "Cat", rank: "1", user_zip_code: "10001")
User.create(email: "test13@test.com", password: "password", name: "Stephanie", rank: "1", user_zip_code: "10001")
User.create(email: "test14@test.com", password: "password", name: "Yi", rank: "2", user_zip_code: "10001")
User.create(email: "test15@test.com", password: "password", name: "Erol", rank: "1", user_zip_code: "10001")
User.create(email: "test16@test.com", password: "password", name: "Greta", rank: "1", user_zip_code: "10001")
User.create(email: "test17@test.com", password: "password", name: "Natalia", rank: "1", user_zip_code: "10001")



# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
